version: "3.8"
networks:
  network:
services:
  couchdb-0:
    environment:
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      COUCHDB_USER: ${COUCHDB_USER}
      NODENAME: couchdb-0.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-0.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}0:5984"
    volumes:
      - "volume-0:/opt/couchdb/data"
      - "cfg-couch-0:/opt/couchdb/etc/local.d"
  couchdb-1:
    environment:
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      COUCHDB_USER: ${COUCHDB_USER}
      NODENAME: couchdb-1.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-1.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}1:5984"
    volumes:
      - "volume-1:/opt/couchdb/data"
      - "cfg-couch-1:/opt/couchdb/etc/local.d"
  couchdb-2:
    environment:
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      COUCHDB_USER: ${COUCHDB_USER}
      NODENAME: couchdb-2.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-2.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}2:5984"
    volumes:
      - "volume-2:/opt/couchdb/data"
      - "cfg-couch-2:/opt/couchdb/etc/local.d"
volumes:
  volume-0:
  cfg-couch-0:
  volume-1:
  cfg-couch-1:
  volume-2:
  cfg-couch-2: