version: "3.8"
networks:
  network:
services:
  server-0:
    environment:
      COUCHDB_PASSWORD: password
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-0
      ERL_FLAGS: "-setcookie obligatorycookie"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - "5984:5984"
    volumes:
      - "volume-0:/opt/couchdb/data"
      - "cfg-couch-0:/opt/couchdb/etc/local.d"
  server-1:
    environment:
      COUCHDB_PASSWORD: password
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-1
      ERL_FLAGS: "-setcookie obligatorycookie"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-1.docker.com
    ports:
      - "15984:5984"
    volumes:
      - "volume-1:/opt/couchdb/data"
      - "cfg-couch-1:/opt/couchdb/etc/local.d"
  server-2:
    environment:
      COUCHDB_PASSWORD: password
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-2
      ERL_FLAGS: "-setcookie obligatorycookie"
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-2.docker.com
    ports:
      - "25984:5984"
    volumes:
      - "volume-2:/opt/couchdb/data"
      - "cfg-couch-2:/opt/couchdb/etc/local.d"
volumes:
  volume-0:
  cfg-couch-0:
  volume-1:
  cfg-couch-1:
  volume-2:
  cfg-couch-2: